spring:
  application:
    name: eureka-client-DB
    fetchRegistry: true

  server:
    port: 1902
  eureka:
    instance:
      hostname: localhost
    client:
      serviceUrl.defaultZone: ${EUREKA_URI:http://localhost:9000/eureka}

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false